# This config tells buildit.py what sections go where when building the syntax
# plugin.  This should make building syntax files for other editors easier.

pluginName: lslvimazing
language: Linden Scripting Language (LSL)
editor: vim
structure:
- name: ftdetect  
  source: plug-ftdetect.txt
  filename: lsl.vim
  directory: lslvimazing/ftdetect/
- name: ftplugin
  source: plug-ftplugin.txt
  filename: lsl.vim
  directory: lslvimazing/ftplugin/
- name: indent
  source: plug-indent.txt
  filename: lsl.vim
  directory: lslvimazing/indent/
- name: syntax
  source: plug-syntax.txt
  filename: lsl.vim
  directory: lslvimazing/syntax/
- name: root
  source: plug-README.md
  filename: README.md
  directory: lslvimazing/

scraper:
  url: 'http://wiki.secondlife.com/w/index.php?title=Category:'
  pageBegin: 'Pages in category'
  pageEnd: 'class="printfooter"'
  searchTerm: '<li><a href="/wiki/'
  delim: ['>','<']
  ignore: ['\n', '(', '(previous 200) (', 'next 200', 'previous 200', '(previous 200) (next 200)\n']
  queries:
  - name: 'LSL_Functions'
    page: 'LSL_Functions&pagefrom='
    rules: ['firstLower']
    replace: [False]
  - name: 'LSL_Events'
    page: 'LSL_Events&pagefrom='
    rules: ['lower']
    replace: [' ','_']
  - name: 'LSL_Constants'
    page: 'LSL_Constants&pagefrom='
    rules: ['upper']
    replace: [' ','_']
