# This config tells buildit.py what sections go where when building the syntax
# plugin.  This should make building syntax files for other editors easier.

pluginName: lslvimazing
editor: vim
structure:
- name: ftdetect  
  source: plug-ftdetect.txt
  file: lsl.vim
  directory: lslvimazing/ftdetect
- name: ftplugin
  contents: plug-ftplugin.txt
  file: lsl.vim
  directory: lslvimazing/ftplugin
- name: indent
  contents: plug-indent.txt
  file: lsl.vim
  directory: lslvimazing/indent
- name: syntax
  contents: plug-syntax.txt
  file: lsl.vim
  directory: lslvimazing/syntax
- name: root
  contents: plug-README.md
  file: README.md
  directory: lslvimazing

scraper:
  url: http://wiki.secondlife.com/w/index.php?title=Category:
  pageBegin: 'Pages in category'
  pageEnd: 'class="printfooter"'
  searchTerm: '<li><a href="/wiki/'
  delim: ['>','<']
  queries:
  - name: LSL_Functions
    page: LSL_Functions&pagefrom=
    rules:
