# This config tells buildit.py what sections go where when building the syntax
# plugin.  This should make building syntax files for other editors easier.

pluginName: lslvimazing
pluginLocation: ''                  # Empty string is same dir as lslvimazing-builder
editor: vim
structure:
  dirs:
    -ftdetect
       source: plug-ftdetect.txt    # Puts txt contents in pluginName/ftdetect/lsl.vim
       name: lsl.vim
     ftplugin
       contents: plug-ftplugin.txt
       name: lsl.vim
     indent
       contents: plug-indent.txt
       name: lsl.vim
     syntax
       contents: plug-syntax.txt
       name: lsl.vim
  xtra:
    -README.md
